# Generated by Django 4.2.1 on 2023-06-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_blog_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('product_weight', models.CharField(max_length=30)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_tagline', models.CharField(max_length=30)),
                ('product_description', models.TextField()),
                ('product_price', models.CharField(max_length=20)),
                ('del_price', models.CharField(max_length=20)),
            ],
        ),
    ]
