# Generated by Django 4.2.1 on 2023-06-22 05:14

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='update/', verbose_name='Image'),
        ),
    ]
