# Generated by Django 4.2.1 on 2023-06-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_tagline',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vf', 'Vegitablesfruits'), ('ms', 'Meatsseafood'), ('bd', 'Breakfastdairy'), ('ff', 'Frozenfood')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
